apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-httpserver
  name: go-httpserver
spec:
  ports:
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: go-httpserver
  type: NodePort
status:
  loadBalancer: {}
